### ISSUE TITLE
License Key Value Stored in config/project/project.yaml

### ISSUE THREAD

**Issue by curtismorte** [surprisehighway/craft-avatax#30]
Hey Guys,
Great plugin!

I happened to notice that the `sandboxLicenseKey` and `licenseKey` value is getting stored into the project configuration file (`/config/project/project.yaml`). A solution to avoid committing sensitive values into version control is to use an [environmental configuration](https://craftcms.com/docs/3.x/config/#control-panel-settings).

[**Per the Craft documentation:**
](https://craftcms.com/docs/3.x/extend/environmental-settings.html)

> Plugin settings that may need to change per-environment, or contain sensitive information, should be implemented as environmental settings.

For example, the current Avatax definition is:
```yaml
avatax:
    edition: standard
    enabled: true
    schemaVersion: 2.0.0
    settings:
      accountId: ''
      certCaptureClientId: null
      certCapturePassword: null
      certCaptureUsername: null
      companyCode: ''
      debug: ''
      defaultDiscountCode: OD010000
      defaultShippingCode: FR
      defaultTaxCode: P0000000
      enableAddressValidation: ''
      enableCommitting: ''
      enablePartialRefunds: ''
      enableTaxCalculation: ''
      environment: sandbox
      licenseKey: ''
      sandboxAccountId: ''
      sandboxCompanyCode: ''
      sandboxLicenseKey: ''
      shipFromCity: ''
      shipFromCountry: ''
      shipFromName: ''
      shipFromState: ''
      shipFromStreet1: ''
      shipFromStreet2: ''
      shipFromStreet3: ''
      shipFromZipCode: ''
```

**With the environment settings specified above, that could turn into:**
```yaml
avatax:
    edition: standard
    enabled: true
    schemaVersion: 2.0.0
    settings:
      ...
      licenseKey: '$AVALARA_LICENSE_KEY'
      sandboxLicenseKey: '$AVALARA_SANDBOX_LICENSE_KEY'
      ...
```
> Assuming you were to set the values `AVALARA_LICENSE_KEY` `AVALARA_SANDBOX_LICENSE_KEY` in your `/.env` file.
